name: Deploy and Test Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure
      run: |
        az deployment group create --name "deploy-web-app" \
                                    --resource-group "your-resource-group-name" \
                                    --template-file "./deploy/webapp.bicep" \
                                    --parameters environmentType=nonprod

    - name: Run tests
      run: |
        # Add your test commands here
